---
- name: "📌 STATUS: Configurando ambiente Golang"
  ansible.builtin.debug:
    msg: "🦫 LANG: Instalando compilador Go..."
  when: languages_features.golang | default(true)

- name: Instalar Golang (Repository)
  ansible.builtin.package:
    name: 
      - golang
    state: present
  when: 
    - languages_features.golang | default(true)
    - ansible_facts['os_family'] == 'Debian'
  tags: [go, golang]

- name: Instalar Golang (Repository)
  ansible.builtin.package:
    name:
      - go
    state: present
  when: 
    - languages_features.golang | default(true)
    - ansible_facts['distribution'] == 'Void'
  tags: [go, golang]
