---
- name: Carregar tarefas de Python
  ansible.builtin.include_tasks: python.yml
  tags: [python]

- name: Carregar tarefas de Node.js
  ansible.builtin.include_tasks: node.yml
  tags: [node]

- name: Carregar tarefas de Rust
  ansible.builtin.include_tasks: rust.yml
  tags: [rust]

- name: Carregar tarefas de Golang
  ansible.builtin.include_tasks: go.yml
  tags: [go, golang]
