devtools_packages:
  - btop
  - git
  - stow
  - fzf
  - direnv
  - lsd
  - python-pipx
  - unzip
  - curl
  - wget
  - tmux
  - kubectl
  - ansible
  - base-devel
  - luarocks
  - ripgrep
  - fd
  - imagemagick
  - ghostscript
  - cmake
  - tree-sitter
  - git-delta
  - broot
  - bat
