---
- name: Instalar Docker
  ansible.builtin.package:
    name:
      - docker
      - docker-buildx
      - docker-compose
    state: present

- name: Habilitar serviço Docker
  ansible.builtin.service:
    name: docker
    enabled: true
    state: started
  when: ansible_facts['service_mgr'] == "systemd"
