---
- name: Instalar Docker em Debian/Ubuntu
  ansible.builtin.include_tasks: debian.yml
  when: ansible_facts['os_family'] == "Debian"

- name: Instalar Docker em Void Linux
  ansible.builtin.include_tasks: void.yml
  when: ansible_facts['distribution'] == "Void"

- name: Adiciona usuário ao grupo docker
  ansible.builtin.user:
    name: "{{ user_id }}"
    groups: docker
    append: true
